export const implementedDeclaredRoutes = {
  COMPONENT: { methods: ['GET', 'PATCH', 'PUT', 'DELETE'], auth: 'session', aliases: ['/api/v1/components/:id'] },
  COMPONENT_REVISION_CODE: { methods: ['GET'], auth: 'session', aliases: ['/api/v1/components/:id/revision/:revisionId/code'] },
  COMPONENT_REVISIONS: { methods: ['GET'], auth: 'session', aliases: ['/api/v1/components/:id/revisions'] },
  DESIGN_SYSTEMS: { methods: ['GET', 'POST'], auth: 'session', aliases: ['/api/v1/design-systems'] },
  DESIGN_SYSTEM: { methods: ['GET', 'PATCH', 'PUT', 'DELETE'], auth: 'session', aliases: ['/api/v1/design-systems/:id'] },
  DESIGN_SYSTEM_EXTRACT_FROM_URL: { methods: ['POST'], auth: 'session', aliases: ['/api/v1/design-systems/extract-from-url'] },
  DESIGN_SYSTEM_EXTRACT_JOB_STATUS: { methods: ['GET'], auth: 'session', aliases: ['/api/v1/design-systems/extract-from-url/:jobId'] },
  FONTS: { methods: ['GET', 'POST'], auth: 'session', aliases: ['/api/v1/fonts'] },
  FONT: { methods: ['GET'], auth: 'session', aliases: ['/api/v1/fonts/:id'] },
  LIBRARIES: { methods: ['GET', 'POST'], auth: 'session', aliases: ['/api/v1/libraries'] },
  LIBRARY: { methods: ['GET'], auth: 'session', aliases: ['/api/v1/libraries/:id'] },
  LIBRARY_ACTIVE: { methods: ['POST', 'PUT', 'PATCH'], auth: 'session', aliases: ['/api/v1/libraries/:id/active'] },
  LIBRARY_COMPONENTS: { methods: ['GET', 'POST'], auth: 'session', aliases: ['/api/v1/libraries/:id/components'] },
  LIBRARY_COMPONENT_COPY_TO_PROJECT: { methods: ['POST'], auth: 'session', aliases: ['/api/v1/libraries/:id/components/:componentId/copy-to-project'] },
  LIBRARY_COPY: { methods: ['POST'], auth: 'session', aliases: ['/api/v1/libraries/:id/copy'] },
  PROJECTS: { methods: ['GET', 'POST'], auth: 'session', aliases: ['/users/me/projects', '/api/v1/projects'] },
  PROJECT: { methods: ['GET', 'PATCH', 'PUT', 'DELETE'], auth: 'session', aliases: ['/api/v1/projects/:id'] },
  PROJECT_COMPONENTS: { methods: ['GET', 'POST'], auth: 'session', aliases: ['/api/v1/projects/:id/components'] },
  SKILL: { methods: ['GET', 'PATCH', 'PUT', 'DELETE'], auth: 'session', aliases: ['/api/v1/skills/:id'] },
  SKILL_FILES: { methods: ['GET'], auth: 'session', aliases: ['/api/v1/skills/:id/files'] },
  SKILL_FILE_CONTENT: { methods: ['GET'], auth: 'session', aliases: ['/api/v1/skills/:id/files/content'] },
  USER_SELF: { methods: ['GET'], auth: 'session', aliases: ['/api/v1/users/me'] },
  USER_CHAT_THREADS: { methods: ['GET', 'POST'], auth: 'session', aliases: ['/api/v1/users/me/chat-threads'] },
  USER_CHAT_THREAD_MESSAGES: { methods: ['GET', 'POST'], auth: 'session', aliases: ['/api/v1/users/me/chat-threads/:threadId/messages'] },
  USER_DESIGN_SYSTEMS: { methods: ['GET'], auth: 'session', aliases: ['/api/v1/users/me/design-systems'] },
  USER_FONTS: { methods: ['GET'], auth: 'session', aliases: ['/api/v1/users/me/fonts'] },
  USER_SKILLS_IMPORT: { methods: ['POST'], auth: 'session', aliases: ['/api/v1/users/me/skills/import'] },
  USERS_PROJECTS: { methods: ['GET'], auth: 'session', aliases: ['/api/v1/users/me/projects'] },
  USER_SKILLS: { methods: ['GET', 'POST'], auth: 'session', aliases: ['/skills', '/api/v1/users/me/skills'] },
};

export const intentionallyUnsupportedPhase0 = new Set([
  'COMPONENT_COPY', 'COMPONENT_COPY_TO_NEW_PROJECT', 'COMPONENT_COPY_TO_PROJECT', 'COMPONENT_EDIT_ELEMENT', 'COMPONENT_FLOW_CHILD',
  'COMPONENT_LIKE', 'COMPONENT_REVISION', 'COMPONENT_REVISION_DOWNLOAD_KEY', 'COMPONENT_REVISION_DOWNLOAD_ZIP', 'COMPONENT_REVISION_RETRY',
  'COMPONENT_SCREENSHOT', 'COMPONENT_REVISION_VARIATIONS', 'COMPONENT_REVISIONS_QUEUE', 'COMPONENT_REVISION_JOB', 'COMPONENT_SEND_TO_LIBRARY',
  'COMPONENT_VISUAL_EDIT_COMMIT', 'COMPONENTS_BATCH', 'COMPONENTS_LIKED', 'COMPONENTS_SEND_TO_LIBRARY', 'COMPONENTS_TOP',
  'DESIGN_SYSTEM_DESIGN_MD_PREVIEW', 'DESIGN_SYSTEM_DESIGN_MD_PREVIEW_JOB_STATUS',
  'IMAGE_COPY', 'IMAGE_FINALIZE', 'IMAGE_URL', 'IMAGES_BATCH',
  'LIBRARY_INSTALL', 'LIBRARY_PROMOTE_DEFAULT',
  'PROJECT_COMPONENTS_SYNC', 'PROJECT_CONTEXT', 'PROJECT_COPY', 'PROJECT_IMAGES', 'PROJECT_LEAVE', 'PROJECT_MAKE_SHARED', 'PROJECT_MEMBER',
  'PROJECT_MOVE_TO_ORGANIZATION', 'PROJECT_OPEN', 'PROJECT_SHARE', 'PROJECTS_POPULAR', 'PROJECTS_PUBLIC', 'PROJECTS_TOP_VIEWED',
  'USER_ASSETS_UPLOAD_URL', 'USER_CHAT_THREAD', 'USER_ONBOARDING',
  'USER_ONBOARDING_INITIALIZE', 'USER_ONBOARDING_SUGGESTION', 'USER_ONBOARDING_SYNC', 'DESIGN',
]);

export const runtimeRoutes = [
  { path: '/health', methods: ['GET'], auth: 'public' },
  { path: '/api/session', methods: ['GET'], auth: 'same-origin-bootstrap', canonical: '/api/v1/session' },
  { path: '/projects/:id/canvas', methods: ['GET', 'PUT', 'PATCH'], auth: 'session', canonical: '/api/v1/projects/:id/canvas' },
  { path: '/generate', methods: ['POST'], auth: 'session', canonical: '/api/v1/generate' },
  { path: '/components/:id/files', methods: ['GET'], auth: 'session', canonical: '/api/v1/components/:id/files' },
  { path: '/components/:id/preview', methods: ['GET'], auth: 'session', canonical: '/api/v1/components/:id/preview' },
  { path: '/components/:id/candidates', methods: ['POST'], auth: 'session', canonical: '/api/v1/components/:id/candidates' },
  { path: '/components/:id/edit-sessions', methods: ['POST'], auth: 'session', canonical: '/api/v1/components/:id/edit-sessions' },
  { path: '/edit-sessions/:id', methods: ['GET', 'DELETE'], auth: 'session', canonical: '/api/v1/edit-sessions/:id' },
  { path: '/edit-sessions/:id/operations', methods: ['POST'], auth: 'session', canonical: '/api/v1/edit-sessions/:id/operations' },
  { path: '/edit-sessions/:id/done', methods: ['POST'], auth: 'session', canonical: '/api/v1/edit-sessions/:id/done' },
  { path: '/revisions/:id/mapping', methods: ['GET'], auth: 'session', canonical: '/api/v1/revisions/:id/mapping' },
  { path: '/revisions/:id/compare', methods: ['GET'], auth: 'session', canonical: '/api/v1/revisions/:id/compare' },
  { path: '/components/:id/checkout', methods: ['POST'], auth: 'session', canonical: '/api/v1/components/:id/checkout' },
  { path: '/revisions/:id/restore', methods: ['POST'], auth: 'session', canonical: '/api/v1/revisions/:id/restore' },
  { path: '/components/:id/variants', methods: ['GET', 'POST'], auth: 'session', canonical: '/api/v1/components/:id/variants' },
  { path: '/variant-groups/:id', methods: ['GET'], auth: 'session', canonical: '/api/v1/variant-groups/:id' },
  { path: '/candidates/:id', methods: ['GET'], auth: 'session', canonical: '/api/v1/candidates/:id' },
  { path: '/builds/:id', methods: ['GET'], auth: 'session', canonical: '/api/v1/builds/:id' },
  { path: '/builds/:id/run', methods: ['POST'], auth: 'session', canonical: '/api/v1/builds/:id/run' },
  { path: '/builds/:id/events', methods: ['GET'], auth: 'session', canonical: '/api/v1/builds/:id/events' },
  { path: '/revisions/:id/preview', methods: ['GET'], auth: 'session', canonical: '/api/v1/revisions/:id/preview' },
  { path: '/revisions/:id/retry-build', methods: ['POST'], auth: 'session', canonical: '/api/v1/revisions/:id/retry-build' },
  { path: '/revisions/:id/screenshots', methods: ['POST'], auth: 'session', canonical: '/api/v1/revisions/:id/screenshots' },
  { path: '/provider-configs', methods: ['GET', 'POST'], auth: 'session', canonical: '/api/v1/provider-configs' },
  { path: '/provider-configs/:id', methods: ['PUT', 'PATCH'], auth: 'session', canonical: '/api/v1/provider-configs/:id' },
  { path: '/projects/:id/chat/threads', methods: ['GET', 'POST'], auth: 'session', canonical: '/api/v1/projects/:id/chat/threads' },
  { path: '/projects/:id/chat/threads/:threadId/messages', methods: ['GET'], auth: 'session', canonical: '/api/v1/projects/:id/chat/threads/:threadId/messages' },
  { path: '/projects/:id/chat/threads/:threadId/runs', methods: ['POST'], auth: 'session', canonical: '/api/v1/projects/:id/chat/threads/:threadId/runs' },
  { path: '/projects/:id/chat/runs', methods: ['POST'], auth: 'session', canonical: '/api/v1/projects/:id/chat/runs' },
  { path: '/thread-runs/:id', methods: ['GET'], auth: 'session', canonical: '/api/v1/thread-runs/:id' },
  { path: '/thread-runs/:id/events', methods: ['GET'], auth: 'session', canonical: '/api/v1/thread-runs/:id/events' },
  { path: '/thread-runs/:id/cancel', methods: ['POST'], auth: 'session', canonical: '/api/v1/thread-runs/:id/cancel' },
  { path: '/jobs/:id/retry', methods: ['POST'], auth: 'session', canonical: '/api/v1/jobs/:id/retry' },
  { path: '/design-systems/:id/versions', methods: ['GET', 'POST'], auth: 'session', canonical: '/api/v1/design-systems/:id/versions' },
  { path: '/projects/:id/design-system', methods: ['PUT', 'PATCH'], auth: 'session', canonical: '/api/v1/projects/:id/design-system' },
  { path: '/theme-extractions', methods: ['POST'], auth: 'session', canonical: '/api/v1/theme-extractions' },
  { path: '/theme-extractions/:id/review', methods: ['POST'], auth: 'session', canonical: '/api/v1/theme-extractions/:id/review' },
  { path: '/projects/:id/fonts/:fontId', methods: ['PUT', 'PATCH'], auth: 'session', canonical: '/api/v1/projects/:id/fonts/:fontId' },
  { path: '/projects/:id/skills/:skillId', methods: ['PUT', 'PATCH'], auth: 'session', canonical: '/api/v1/projects/:id/skills/:skillId' },
  { path: '/projects/:id/libraries/:libraryId', methods: ['PUT', 'PATCH'], auth: 'session', canonical: '/api/v1/projects/:id/libraries/:libraryId' },
  { path: '/projects/:id/canvas/library-items', methods: ['POST'], auth: 'session', canonical: '/api/v1/projects/:id/canvas/library-items' },
  { path: '/projects/:id/operational-context', methods: ['GET'], auth: 'session', canonical: '/api/v1/projects/:id/operational-context' },
  { path: '/projects/:id/imports/web', methods: ['GET', 'POST'], auth: 'session', canonical: '/api/v1/projects/:id/imports/web' },
  { path: '/imports/:id', methods: ['GET'], auth: 'session', canonical: '/api/v1/imports/:id' },
  { path: '/imports/:id/convert', methods: ['POST'], auth: 'session', canonical: '/api/v1/imports/:id/convert' },
  { path: '/phase7/jobs/:id', methods: ['GET'], auth: 'session', canonical: '/api/v1/phase7/jobs/:id' },
  { path: '/projects/:id/capture-tickets', methods: ['POST'], auth: 'session', canonical: '/api/v1/projects/:id/capture-tickets' },
  { path: '/capture-tickets/:id', methods: ['GET'], auth: 'session', canonical: '/api/v1/capture-tickets/:id' },
  { path: '/capture-tickets/:id/submission', methods: ['POST'], auth: 'one-time-origin-scoped-ticket', canonical: '/api/v1/capture-tickets/:id/submission' },
  { path: '/captures/:id', methods: ['GET'], auth: 'session', canonical: '/api/v1/captures/:id' },
  { path: '/search/providers', methods: ['GET', 'POST'], auth: 'session', canonical: '/api/v1/search/providers' },
  { path: '/search/providers/:id', methods: ['PUT', 'PATCH'], auth: 'session', canonical: '/api/v1/search/providers/:id' },
  { path: '/projects/:id/search', methods: ['POST'], auth: 'session-explicit-opt-in', canonical: '/api/v1/projects/:id/search' },
  { path: '/search/queries/:id', methods: ['GET'], auth: 'session', canonical: '/api/v1/search/queries/:id' },
  { path: '/search/queries/:id/results/:index/fetch', methods: ['POST'], auth: 'session-explicit-opt-in', canonical: '/api/v1/search/queries/:id/results/:index/fetch' },
  { path: '/search/contexts/:id', methods: ['GET'], auth: 'session', canonical: '/api/v1/search/contexts/:id' },
  { path: '/projects/:id/imports/figma', methods: ['POST'], auth: 'session', canonical: '/api/v1/projects/:id/imports/figma' },
  { path: '/revisions/:id/figma-exchange', methods: ['GET'], auth: 'session', canonical: '/api/v1/revisions/:id/figma-exchange' },
  { path: '/figma-exchanges/:id', methods: ['GET'], auth: 'session', canonical: '/api/v1/figma-exchanges/:id' },
];
