import { ChangeEvent, useCallback, useEffect, useState } from 'react';
import { api } from '../lib/api';
import { ActionModal } from './ActionModal';

type Entity = Record<string, any> & { id: string; name?: string };
const errorText = (reason: any) => String(reason?.message || reason || 'Action failed');
function Feedback({ error, status }: { error: string; status: string }) { return error ? <div className="diagnostics" role="alert">{error}</div> : status ? <div className="action-status" role="status">{status}</div> : null; }

export function DesignSystemsPage() {
  const [items, setItems] = useState<Entity[]>([]); const [source, setSource] = useState(''); const [review, setReview] = useState<any>(null); const [error, setError] = useState(''); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(''); const [modal, setModal] = useState<{ kind: 'create' | 'version'; item?: Entity } | null>(null); const [value, setValue] = useState('');
  const refresh = useCallback(async () => { try { setItems(await api.get<Entity[]>('/api/v1/design-systems')); } catch (reason) { setError(errorText(reason)); } }, []); useEffect(() => { void refresh(); }, [refresh]);
  const perform = async (name: string, task: () => Promise<void>) => { if (busy) return; setBusy(name); setError(''); setStatus(''); try { await task(); } catch (reason) { setError(errorText(reason)); } finally { setBusy(''); } };
  const extract = () => perform('extract', async () => { setReview(await api.post('/api/v1/theme-extractions', source.trim().startsWith('https://') ? { url: source.trim() } : { css: source })); setStatus('Extraction is ready for explicit review.'); });
  const open = (kind: 'create' | 'version', item?: Entity) => { setModal({ kind, item }); setValue(kind === 'create' ? 'New design system' : item?.markdown || `# ${item?.name || 'Design system'}`); setError(''); setStatus(''); };
  const save = () => perform('modal', async () => { if (modal?.kind === 'create') { await api.post('/api/v1/design-systems', { name: value.trim() }); setStatus('Design system created with immutable v1.'); } else if (modal?.item) { await api.post(`/api/v1/design-systems/${modal.item.id}/versions`, { markdown: value }); setStatus('New immutable design-system version created.'); } await refresh(); setModal(null); });
  return <><Feedback error={error} status={status}/><section className="theme-extractor card"><h3>Reviewed theme extraction</h3><p className="meta">Paste CSS or a credential-free HTTPS URL. Nothing is activated until you inspect and approve the token proposal.</p><textarea value={source} onChange={(event) => setSource(event.target.value)} placeholder={'https://example.com/theme.css\n—or—\n:root { --background: #fff; }'}/><button onClick={extract} disabled={Boolean(busy) || !source.trim()} title={!source.trim() ? 'Paste CSS or a credential-free HTTPS URL first.' : ''}>{busy === 'extract' ? 'Extracting…' : 'Extract for review'}</button>{review?.status === 'pending' && <div className="review-proposal"><pre>{JSON.stringify(review.proposal, null, 2)}</pre><div className="row"><button className="primary" disabled={Boolean(busy)} onClick={() => perform('approve', async () => { const approved = await api.post<any>(`/api/v1/theme-extractions/${review.id}/review`, { approved: true, proposal: review.proposal }); setReview(approved); await refresh(); setStatus('Approved and created immutable v1.'); })}>{busy === 'approve' ? 'Approving…' : 'Approve and create immutable v1'}</button><button className="danger" disabled={Boolean(busy)} onClick={() => perform('reject', async () => { setReview(await api.post(`/api/v1/theme-extractions/${review.id}/review`, { approved: false })); setStatus('Proposal rejected.'); })}>Reject</button></div></div>}{review && review.status !== 'pending' && <p className="meta">Review {review.status}{review.versionId ? ` · ${review.versionId}` : ''}</p>}</section><div className="grid">{items.map((item) => <article className="card" key={item.id}><h3>{item.name}</h3><div className="meta">Exact v{item.currentVersion?.version || '?'} · {item.currentVersion?.id || 'not compiled'}</div><p>{item.markdown || item.prompt}</p><div className="row"><button disabled={Boolean(busy)} onClick={() => open('version', item)}>New version</button></div></article>)}</div><button className="primary floating-create" disabled={Boolean(busy)} onClick={() => open('create')}>New design system</button><ActionModal open={Boolean(modal)} title={modal?.kind === 'create' ? 'Create design system' : `New version of ${modal?.item?.name || 'design system'}`} description={modal?.kind === 'create' ? 'A compiled immutable v1 will be created.' : 'Edit DESIGN.md. Saving creates a new immutable version.'} confirmLabel={modal?.kind === 'create' ? 'Create design system' : 'Create version'} pending={busy === 'modal'} error={error} field={{ label: modal?.kind === 'create' ? 'Name' : 'DESIGN.md', value, onChange: setValue, required: true, multiline: modal?.kind === 'version' }} onCancel={() => setModal(null)} onConfirm={save}/></>;
}

function CollectionCreatePage({ kind }: { kind: 'library' | 'skill' }) {
  const plural = kind === 'library' ? 'libraries' : 'skills'; const title = kind === 'library' ? 'Library' : 'Skill';
  const [items, setItems] = useState<Entity[]>([]); const [error, setError] = useState(''); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false); const [open, setOpen] = useState(false); const [name, setName] = useState(`New ${kind}`);
  const refresh = useCallback(async () => { try { setItems(await api.get<Entity[]>(`/api/v1/${plural}`)); } catch (reason) { setError(errorText(reason)); } }, [plural]); useEffect(() => { void refresh(); }, [refresh]);
  const create = async () => { if (busy) return; setBusy(true); setError(''); setStatus(''); try { await api.post(`/api/v1/${plural}`, kind === 'skill' ? { name: name.trim(), description: 'Explicitly selected local skill' } : { name: name.trim() }); await refresh(); setOpen(false); setStatus(`${title} created.`); } catch (reason) { setError(errorText(reason)); } finally { setBusy(false); } };
  return <><Feedback error={error} status={status}/>{kind === 'skill' && <SkillImport busy={busy} setBusy={setBusy} setError={setError} setStatus={setStatus} refresh={refresh}/>}<div className="grid">{items.map((item) => <article className="card" key={item.id}><h3>{item.name}{item.builtin ? ' · built-in' : ''}</h3>{kind === 'library' ? <><div className="meta">{item.membershipCount} exact immutable revision{item.membershipCount === 1 ? '' : 's'}</div>{item.members?.map((member: any) => <div className="library-member" key={member.revisionId}><b>{member.name}</b><small>{member.revisionId} · {member.status}</small></div>)}</> : <><div className="meta">Immutable v{item.currentVersion?.version || '?'} · {item.optionalActivation ? 'description-safe optional activation' : 'explicit selection only'}</div><p>{item.description}</p></>}</article>)}</div><button className="primary floating-create" disabled={busy} onClick={() => { setName(`New ${kind}`); setError(''); setOpen(true); }}>New {kind}</button><ActionModal open={open} title={`Create ${kind}`} description={kind === 'library' ? 'Libraries pin exact immutable component revisions.' : 'Skills activate only through explicit project selection.'} confirmLabel={`Create ${kind}`} pending={busy} error={error} field={{ label: `${title} name`, value: name, onChange: setName, required: true }} onCancel={() => setOpen(false)} onConfirm={create}/></>;
}

function SkillImport({ busy, setBusy, setError, setStatus, refresh }: any) {
  const ingest = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || busy) return; setBusy(true); setError(''); setStatus(''); try { const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ''; for (const byte of bytes) binary += String.fromCharCode(byte); await api.post('/api/v1/skills/import', { name: file.name, base64: btoa(binary) }); await refresh(); setStatus(`Imported ${file.name}.`); } catch (reason) { setError(errorText(reason)); } finally { setBusy(false); event.target.value = ''; } };
  return <label className="upload-control">{busy ? 'Importing…' : 'Import text-only .skill or <5 MiB zip'}<input disabled={busy} type="file" accept=".skill,.zip" onChange={ingest}/></label>;
}
export function LibrariesPage() { return <CollectionCreatePage kind="library"/>; }
export function SkillsPage() { return <CollectionCreatePage kind="skill"/>; }
