import { ChangeEvent, FormEvent, useCallback, useEffect, useState } from 'react';
import { api } from '../lib/api';

type WebImport = { id: string; requestedUrl: string; finalUrl: string; fetchedAt: string; rightsWarning: string; diagnostics: { code: string; message: string }[]; assets: unknown[] };
type SearchProvider = { id: string; label: string; kind: string; endpointUrl?: string; enabled: boolean };
const errorText = (reason: any) => String(reason?.message || reason || 'Action failed');

export function WebImportPanel({ projectId, navigate }: { projectId: string; navigate: (path: string) => void }) {
  const [url, setUrl] = useState('https://'); const [name, setName] = useState(''); const [ingestAssets, setIngestAssets] = useState(false); const [imports, setImports] = useState<WebImport[]>([]); const [selected, setSelected] = useState<WebImport | null>(null); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [status, setStatus] = useState('');
  const [ticketOrigin, setTicketOrigin] = useState('https://'); const [ticket, setTicket] = useState<any>(null); const [tickets, setTickets] = useState<any[]>([]);
  const [figmaText, setFigmaText] = useState('');
  const [providers, setProviders] = useState<SearchProvider[]>([]); const [providerId, setProviderId] = useState(''); const [providerLabel, setProviderLabel] = useState('Local fixture search'); const [providerKind, setProviderKind] = useState<'fixture' | 'endpoint'>('fixture'); const [providerEndpoint, setProviderEndpoint] = useState('https://'); const [queryText, setQueryText] = useState(''); const [searchOptIn, setSearchOptIn] = useState(false); const [searchRecord, setSearchRecord] = useState<any>(null); const [contexts, setContexts] = useState<Record<number, any>>({});
  const refresh = useCallback(async () => { const items = await api.get<WebImport[]>(`/api/v1/projects/${projectId}/imports/web`); setImports(items); setSelected((current) => current ? items.find((item) => item.id === current.id) || null : items[0] || null); }, [projectId]);
  const refreshTickets = useCallback(async () => { setTickets(await api.get(`/api/v1/projects/${projectId}/capture-tickets`)); }, [projectId]);
  const refreshProviders = useCallback(async () => { const items = await api.get<SearchProvider[]>('/api/v1/search/providers'); setProviders(items); setProviderId((current) => items.some((item) => item.id === current && item.enabled) ? current : items.find((item) => item.enabled)?.id || ''); }, []);
  useEffect(() => { void Promise.all([refresh(), refreshTickets(), refreshProviders()]).catch((reason) => setError(errorText(reason))); }, [refresh, refreshTickets, refreshProviders]);
  useEffect(() => { const timer = window.setInterval(() => { void refreshTickets().catch((reason) => setError(`Capture polling failed: ${errorText(reason)}`)); }, 2_000); return () => window.clearInterval(timer); }, [refreshTickets]);
  const act = async (name: string, task: () => Promise<void>) => { if (busy) return; setBusy(name); setError(''); setStatus(''); try { await task(); } catch (reason) { setError(errorText(reason)); } finally { setBusy(''); } };
  const submit = (event: FormEvent) => { event.preventDefault(); void act('web', async () => { const result = await api.post<any>(`/api/v1/projects/${projectId}/imports/web`, { url, ingestAssets }); setSelected(result.import); setUrl('https://'); await refresh(); setStatus('Sanitized web reference imported with immutable provenance.'); }); };
  const convert = () => { if (!selected) { setError('Select or create a web import first.'); return; } void act('convert', async () => { const result = await api.post<any>(`/api/v1/imports/${selected.id}/convert`, { name: name || undefined }); if (result.build?.status !== 'succeeded') throw new Error(result.conversion?.diagnostics?.[0]?.message || 'Semantic build failed'); setStatus('Semantic conversion built successfully. Opening component…'); navigate(`/components/${result.component.id}`); }); };
  const createTicket = () => void act('ticket', async () => { const issued = await api.post<any>(`/api/v1/projects/${projectId}/capture-tickets`, { origin: ticketOrigin }); setTicket(issued); await refreshTickets(); setStatus('Capture ticket is waiting for the extension. This list polls automatically.'); });
  const figmaFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { setFigmaText(await file.text()); setStatus(`Loaded ${file.name}; review and import when ready.`); setError(''); } catch (reason) { setError(`Unable to read Figma JSON: ${errorText(reason)}`); } finally { event.target.value = ''; } };
  const importFigma = () => void act('figma', async () => { let exchange; try { exchange = JSON.parse(figmaText); } catch { throw new Error('Figma exchange must be valid JSON.'); } const result = await api.post<any>(`/api/v1/projects/${projectId}/imports/figma`, { exchange }); if (result.build?.status !== 'succeeded') throw new Error(result.diagnostics?.[0]?.message || 'Figma import build failed'); setStatus('FigmaExchangeV1 imported and built. Opening component…'); navigate(`/components/${result.component.id}`); });
  const createProvider = () => void act('provider', async () => { const created = await api.post<SearchProvider>('/api/v1/search/providers', { label: providerLabel, kind: providerKind, ...(providerKind === 'endpoint' ? { endpointUrl: providerEndpoint } : {}), enabled: true }); await refreshProviders(); setProviderId(created.id); setStatus('Search provider created and enabled.'); });
  const toggleProvider = (provider: SearchProvider) => void act('provider-toggle', async () => { await api.patch(`/api/v1/search/providers/${provider.id}`, { enabled: !provider.enabled }); await refreshProviders(); setStatus(`${provider.label} ${provider.enabled ? 'disabled' : 'enabled'}.`); });
  const search = (event: FormEvent) => { event.preventDefault(); void act('search', async () => { const result = await api.post(`/api/v1/projects/${projectId}/search`, { query: queryText, providerId, optIn: searchOptIn }); setSearchRecord(result); setContexts({}); setStatus('Search results recorded immutably. Result pages have not been fetched.'); }); };
  const fetchResult = (index: number) => void act(`fetch:${index}`, async () => { const context = await api.post<any>(`/api/v1/search/queries/${searchRecord.id}/results/${index}/fetch`, { optIn: true }); setContexts((value) => ({ ...value, [index]: context })); setStatus(`Result ${index + 1} explicitly fetched as untrusted reference context.`); });
  const providerProblem = !providers.length ? 'Create and enable a search provider first.' : !providerId ? 'Select an enabled search provider.' : '';
  const backendOrigin = location.origin;
  return <div className="web-import-page"><header className="web-import-heading"><div><button onClick={() => navigate(`/projects/${projectId}`)}>← Canvas</button><h3>Web references and exchange</h3><p>Remote content stays untrusted and inert. MyPath never runs imported scripts or sends cookies.</p></div></header>
    {error && <div className="diagnostics" role="alert">{error}</div>}{status && !error && <div className="action-status" role="status">{status}</div>}
    <div className="web-import-columns"><section className="card"><h3>Safe full-page import</h3><form onSubmit={submit}><label>Credential-free HTTPS URL<input type="url" required pattern="https://.*" value={url} onChange={(event) => setUrl(event.target.value)}/></label><label className="checkbox"><input type="checkbox" checked={ingestAssets} onChange={(event) => setIngestAssets(event.target.checked)}/>Fetch and locally ingest up to 8 approved image assets</label><button className="primary" disabled={Boolean(busy)}>{busy === 'web' ? 'Importing…' : 'Import sanitized page'}</button></form><p className="rights-warning">Only import material you have the right to use. Review copyright, licenses, attribution, and trademarks.</p><h4>Immutable imports</h4>{imports.map((item) => <button className={selected?.id === item.id ? 'web-import-item active' : 'web-import-item'} key={item.id} onClick={() => setSelected(item)}><b>{new URL(item.finalUrl).hostname}</b><small>{new Date(item.fetchedAt).toLocaleString()} · {item.assets.length} local asset(s)</small></button>)}</section>
      <section className="card"><h3>Semantic conversion</h3>{selected ? <><dl><dt>Final URL</dt><dd>{selected.finalUrl}</dd><dt>Safety</dt><dd>Sanitized HTML · no script execution · immutable provenance</dd></dl><label>Design name (optional)<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Imported landing page"/></label><button className="primary" disabled={Boolean(busy)} onClick={convert}>{busy === 'convert' ? 'Converting…' : 'Convert into runnable design'}</button><p className="rights-warning">{selected.rightsWarning}</p>{selected.diagnostics.map((diagnostic) => <div className="diagnostics" key={`${diagnostic.code}:${diagnostic.message}`}>{diagnostic.code}: {diagnostic.message}</div>)}</> : <p>Select or create an import before conversion.</p>}<hr/><h3>Surgical Chrome capture</h3><p>Create a short-lived, origin-scoped, single-use ticket, then paste it into the unpacked MyPath extension.</p><label>Exact HTTPS page origin<input value={ticketOrigin} onChange={(event) => setTicketOrigin(event.target.value)} placeholder="https://example.com"/></label><button disabled={Boolean(busy) || !/^https:\/\/[^/]+\/?$/.test(ticketOrigin)} title={!/^https:\/\/[^/]+\/?$/.test(ticketOrigin) ? 'Enter an exact HTTPS origin first.' : ''} onClick={createTicket}>{busy === 'ticket' ? 'Creating…' : 'Create one-time ticket'}</button>{ticket && <div className="one-time-token"><b>Copy all three values into the extension</b><small>MyPath origin</small><code>{backendOrigin}</code><small>Ticket ID</small><code>{ticket.id}</code><small>One-time token</small><code>{ticket.token}</code><small>Expires {new Date(ticket.expiresAt).toLocaleTimeString()}</small></div>}<div className="capture-ticket-list" aria-live="polite">{tickets.map((item) => <div className="library-member" key={item.id}><b>{item.origin} · {item.state}</b><small>{item.id}{item.captureId ? ` · received capture ${item.captureId}` : ` · expires ${new Date(item.expiresAt).toLocaleTimeString()}`}</small></div>)}</div></section>
      <section className="card"><h3>FigmaExchangeV1 import</h3><p className="meta">Choose or paste a JSON exchange. Imports remain deterministic and provenance-bearing.</p><label className="upload-control">Choose Figma JSON file<input type="file" accept="application/json,.json" disabled={Boolean(busy)} onChange={figmaFile}/></label><textarea value={figmaText} onChange={(event) => setFigmaText(event.target.value)} placeholder={'{"version":"FigmaExchangeV1", ...}'}/><button className="primary" disabled={Boolean(busy) || !figmaText.trim()} title={!figmaText.trim() ? 'Choose or paste FigmaExchangeV1 JSON first.' : ''} onClick={importFigma}>{busy === 'figma' ? 'Importing…' : 'Import and build Figma exchange'}</button></section>
      <section className="card search-card"><h3>Opt-in reference search</h3><p className="meta">Search and each result fetch are separate explicit network actions. Fetched text is always untrusted reference material.</p><div className="provider-create"><label>Provider label<input value={providerLabel} onChange={(event) => setProviderLabel(event.target.value)}/></label><label>Provider type<select value={providerKind} onChange={(event) => setProviderKind(event.target.value as any)}><option value="fixture">Local fixture (no network search)</option><option value="endpoint">HTTPS JSON endpoint</option></select></label>{providerKind === 'endpoint' && <label>Endpoint URL<input type="url" pattern="https://.*" value={providerEndpoint} onChange={(event) => setProviderEndpoint(event.target.value)}/></label>}<button disabled={Boolean(busy) || !providerLabel.trim() || (providerKind === 'endpoint' && !providerEndpoint.startsWith('https://'))} onClick={createProvider}>{busy === 'provider' ? 'Creating…' : 'Create and enable provider'}</button></div>{providers.map((provider) => <div className="library-member" key={provider.id}><label className="checkbox"><input type="radio" name="search-provider" disabled={!provider.enabled} checked={providerId === provider.id} onChange={() => setProviderId(provider.id)}/>{provider.label} · {provider.kind} · {provider.enabled ? 'enabled' : 'disabled'}</label><button disabled={Boolean(busy)} onClick={() => toggleProvider(provider)}>{provider.enabled ? 'Disable' : 'Enable'}</button></div>)}<form onSubmit={search}><label>Reference query<input value={queryText} onChange={(event) => setQueryText(event.target.value)}/></label><label className="checkbox"><input type="checkbox" checked={searchOptIn} onChange={(event) => setSearchOptIn(event.target.checked)}/>I explicitly opt in to this search request</label><button className="primary" disabled={Boolean(busy) || !queryText.trim() || !providerId || !searchOptIn} title={!queryText.trim() ? 'Enter a query.' : providerProblem || (!searchOptIn ? 'Explicitly opt in to this search request.' : '')}>{busy === 'search' ? 'Searching…' : 'Search with explicit opt-in'}</button></form>{searchRecord && <div className="search-results"><pre className="provenance">Immutable search provenance{`\n`}{JSON.stringify(searchRecord.provenance, null, 2)}</pre>{searchRecord.results.map((result: any, index: number) => <article key={result.url}><b>{result.title}</b><small>{result.url}</small><p>{result.snippet}</p><button disabled={Boolean(busy) || Boolean(contexts[index])} onClick={() => fetchResult(index)}>{contexts[index] ? 'Fetched immutably' : busy === `fetch:${index}` ? 'Fetching…' : 'Explicitly fetch this result'}</button>{contexts[index] && <pre className="provenance">Untrusted immutable context{`\n`}{JSON.stringify({ id: contexts[index].id, checksum: contexts[index].contentChecksum, trustClass: contexts[index].trustClass, provenance: contexts[index].provenance }, null, 2)}</pre>}</article>)}</div>}</section>
    </div>{busy && <div className="web-import-status" role="status">{busy === 'web' ? 'Fetching through the safe import boundary…' : 'Action in progress…'}</div>}</div>;
}
